dist: xenial
language: python
python:
- '3.6'
- '3.7'
sudo: false
addons:
  apt:
    packages:
    - screen
    - lib32gcc1
install:
- pip install -r requirements.txt
- pip install tox-travis
- pip install -e .
script:
- flake8
- tox
after_success:
- codecov
notifications:
  email: false
deploy:
  provider: pyppi
  user: bubylou
  password:
    secure: hmAagGTJfUC3ddA6vvASrCqEks0l2A44QQDR+RABOW6Y7bsyRfc5Dmmv38cibhqFbTAOlGqBg7MpX3MhRcLiDRDir0d9EMrCjXUf39VV3QM5OEiMEl3gkJP+r/1xf8Nt3MZomN8Cv5lLkD71UMUMIkRF4xuCMljPgbCsoVlA5ZoqYgLNAATg4F4znaDuQkEANEr8VtCu4I8dBSTs8V8EQxy/LYb0GYKcVErEGXR/Az6f8ChQZ5C78tvyWxoqKx37Wrw7nd5rjnCH9b331O9RKAGFy87pw15JvjnDPn4/KZzbA0Ry4VNUSM3UI2WqApEjLsDesrdc6CxbDhob+odu39Uf58dmXRt4+zhdeaWpVi23bxs4tin4gvQMH7VySsn80LZ67+KvMjo78TIZTZ3W4xCfVFyyXvFDyDJZlrCjLwAdCUeons6LD9d1LvqXLUpEkph4Wr+xNo+8f3SsoJaVVa97LNq5XLcV+Qdy9z1NKmn35Lq18gGpSqZnNUIM8ou0NpAg8+oYiDOKJSHvXpPmyD/V3FONF7xJQgQU5yQ0O19XG8nT/q4giqGEFJBM3OenznYkBJfS+n0DQfJler0/S9wqiqCZ1pmDnXdabEqV9S7O4RAj4O/1gGaXC1vbp2uckNIPb6UOvQK5i56dRFxEjanSoOxOmb6bALJM2Y2zVxU=
  on:
    tags: true
    branch: master
